name: Test, Build & Push to ACR (bootcamp-python)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: bootcamp-python

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. python -m pytest

  build-and-push:
    # Run on push/workflow_dispatch and same-repo PRs; skip only forks.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      # Resolve ACR_NAME from repo vars first, then secrets. Fail if empty.
      - name: Resolve ACR settings
        id: resolve
        shell: bash
        run: |
          set -euo pipefail
          ACR_NAME="${{ vars.ACR_NAME }}"
          if [ -z "$ACR_NAME" ]; then ACR_NAME="${{ secrets.ACR_NAME }}"; fi
          if [ -z "$ACR_NAME" ]; then
            echo "ACR_NAME is empty. Set a repo Variable or Secret named ACR_NAME (e.g., salbootcampacr)." >&2
            exit 1
          fi
          # Write env vars atomically
          printf 'ACR_NAME=%s\n' "$ACR_NAME" >> "$GITHUB_ENV"
          printf 'ACR_LOGIN_SERVER=%s.azurecr.io\n' "$ACR_NAME" >> "$GITHUB_ENV"

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      # Using ACR admin creds for guaranteed push. Swap to SP once AcrPush works.
      - name: ACR login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set image tags
        id: vars
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          BRANCH_TAG=${GITHUB_REF_NAME//\//-}
          echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "branch_tag=$BRANCH_TAG" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.branch_tag }}
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_tag }}
